plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  CountComments: false
  CountAsOne:
    - 'array'
    - 'hash'
    

# ネームスペースの記法を規制しても意味がないため
Style/ClassAndModuleChildren:  
  Enabled: false

# 必ずしも親クラスのメソッドを呼ぶ必要はないため
# 親クラスのメソッドを呼ばないといけない場合は実装ができないのでチェックをする必要がない
Lint/MissingSuper:
  Enabled: false

######################################
# 学習テストのため警告をオフにしている
######################################
RSpec:
  Exclude:
    - 'spec/research/**/*'

Style/MultilineBlockChain:
  Exclude:
    - 'spec/research/**/*'

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/DescribeClass:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/RepeatedSubjectCall:
  Enabled: false