# 基本となるクラス
class BaseEntity
  attr_reader id: Integer
  
  def initialize: (id: Integer) -> void
end

# 継承クラス
class User < BaseEntity
  attr_reader name: String
  attr_reader settings: UserSettings
  
  def initialize: (id: Integer, name: String) -> void
end

# 委譲先のクラス
class UserSettings
  attr_reader theme: String
  
  def initialize: (theme: String) -> void
end

# 関係しないクラス
class Logger
  attr_reader level: String
  
  def initialize: (level: String) -> void
end